### ISSUE TITLE
Tastier Armory Patch: The defname in xpath seems wrong

### ISSUE THREAD

**Issue by Weiche** [AmirAcleAbd/CapesAndArmor#1]
The defname seems wrong, it may be "TC_KidCloak" ? or use "@ParentName" instead of "defName
https://github.com/AmirAcleAbd/CapesAndArmor/blob/a8447b909362ba6d479df7c1bb09477131a68a03/ModPatches/TastierArmory/Patches/TAcape.xml#L14

**Comment by yymirjon** [comment]
yeah it is, it should be @Name instead of defName

**Comment by yymirjon** [comment]
fixed
